Add functions to work with lists of arrays
linhd-postdata/lyrics-similarity-elasticsearch pull request #18
Opened 2021-06-08 12:25 UTC by alvp

2021-06-08 13:12 UTC, aitordiaz requested changes

2021-06-08 13:12 UTC, aitordiaz commented on src/utils.py
> +    :param v2: Embedding vector 1
Please, fix this description

2021-06-08 13:12 UTC, aitordiaz commented on src/utils.py
> +def ind_rl(operation: str, embeddings_list: List[np.array]):
Are these two functions necessary?

2021-06-08 15:43 UTC, kasia-postdata commented on src/utils.py
> +def ind_lr(operation: str, embeddings_list: List[np.array]):
I would like to have one function to compute any composition function from it. Something like:

def composition_function(composition_function_name: str, embedding_list: List[np.array])

where name of the composition function can be: 'sum', 'avg', 'avg_lr', 'avg_rl', 'ind_lr', 'ind_rl', 'joint_lr', 'joint_rl',

2021-06-08 15:43 UTC, kasia-postdata commented on src/utils.py
> +def ind_lr(operation: str, embeddings_list: List[np.array]):
or multiple function with the names 'sum', 'avg', 'avg_lr', 'avg_rl', 'ind_lr', 'ind_rl', 'joint_lr', 'joint_rl'
I don't mind.

But I would like to match the proper function just by one parameter - the name

2021-06-08 15:43 UTC, kasia-postdata commented on src/utils.py
> +    return get_composite_vector(operation, embeddings_list, r2l=True)
Also, I can't see the standard average function implemented here.

2021-06-09 08:41 UTC, aitordiaz commented on src/utils.py
> +def ind_lr(operation: str, embeddings_list: List[np.array]):
Ok, understood 👍 Thanks for the review, I'm working on it.

2021-06-09 10:18 UTC, aitordiaz commented on src/utils.py
> +    return get_composite_vector(operation, embeddings_list, r2l=True)
Done!

2021-06-09 10:19 UTC, aitordiaz commented
To call `composition_function`:

2021-06-09 10:21 UTC, alvp commented on src/utils.py
> +def ind_lr(operation: str, embeddings_list: List[np.array]):
We have taken the first approach, `composition_function(composition_function_name: str, embedding_list: List[np.array])`. 
The only difference is that "**joint_lr**" and "**joint_rl**" are now called "**jnt_lr**" and "**jnt_rl**"

2021-06-09 10:30 UTC, kasia-postdata approved these changes
Perfect! Thx

2021-06-09 10:43 UTC, merged