Architecture proposal
linhd-postdata/lyrics-similarity-elasticsearch pull request #9
Opened 2021-06-02 10:20 UTC by kasia-postdata

2021-06-02 13:33 UTC, alvp requested changes

2021-06-02 13:33 UTC, alvp commented on evaluate_lyrics_models.py
> +    model_dirs = ['']
This can be just a [ ]. 

Also paths shouldn't be strings to ensure proper non-unix path compatibility (Windows, just in case). We should use Path objects: https://docs.python.org/es/3/library/pathlib.html

2021-06-02 13:33 UTC, alvp commented on evaluate_lyrics_models.py
> +from src.classes.ElasticsearchManager import ElasticsearchManager
Add external dependencies to a requirements.txt

2021-06-02 13:33 UTC, alvp commented on src/classes/DataManager.py
> +    def __init__(self, dataset_dir: str, granularities: List[str], model_dirs: List[str], testset_path: str, verbose: bool = True):
Add class documentation

2021-06-02 13:33 UTC, alvp commented on README.md
> +
Add examples of the output

2021-06-02 17:00 UTC, sros-UNED reviewed
I need to understand the testpoint. And I miss the IMC function?.

2021-06-03 08:06 UTC, aitordiaz commented
> I need to understand the testpoint. And I miss the IMC function?.

Once this pull request is approved, I'll add to the utils.py file the functions, so we don't step on each other's toes.

2021-06-03 08:09 UTC, merged